-- ************************* SqlDBM: Databricks *************************
-- **** Generated by SqlDBM: xxx, v2 vs v1 by hazal.sener@sqldbm.com ****

DROP TABLE mySchema.partsupp;
DROP TABLE mySchema.sub_partsupp;
DROP TABLE mySchema.part;
ALTER TABLE mySchema.lineitem
  SET TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
ALTER TABLE mySchema.lineitem
  RENAME COLUMN partkey TO prtkey;
CREATE TABLE mySchema.sub_prtsupp
(
 sub_parsupp_key bigint NOT NULL,
 sub_availqty    int,
 sub_supplycost  decimal(18, 2),
 created_by      varchar(50) NOT NULL, 
 created_date    timestamp NOT NULL 
);
CREATE TABLE mySchema.prt
(
 prtkey       bigint,
 rename       string,
 mfgr         string,
 brand        string,
 type         string,
 size         int,
 container    string,
 retailprice  decimal(18, 2),
 comment      string,
 created_by   varchar(50) NOT NULL, 
 created_date timestamp NOT NULL 
)
USING DELTA
 COMMENT 'parts that we sell to end clients'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, Property = 1);
CREATE TABLE mySchema.prtsupp
(
 prtkey       bigint NOT NULL,
 suppkey      bigint NOT NULL,
 availqty     int,
 supplycost   decimal(18, 2),
 comment      string,
 created_by   varchar(50) NOT NULL, 
 created_date timestamp NOT NULL, 
 CONSTRAINT PK_PK_2_prtsupp PRIMARY KEY (prtkey, suppkey)
)
USING DELTA
 COMMENT 'suppliers and their related stock'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);