-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- Create a temporary view denormalizing nation with regionCREATE TEMPORARY VIEW myDb.mySchema.nation_region
    AS SELECT na.nationkey , na.name , na.regionkey, re.name
         FROM myDb.mySchema.nation AS na 
         INNER JOIN myDb.mySchema.region AS re 
            ON na.regionkey = re.regionkey;
