-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.prt
CREATE TABLE mySchema.prt
(
 prtkey       bigint,
 rename       string,
 mfgr         string,
 brand        string,
 type         string,
 size         int,
 container    string,
 retailprice  decimal(18, 2),
 comment      string,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL -- From template: "w_cerated"
)
USING DELTA
 COMMENT 'parts that we sell to end clients'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, Property = 1);
