-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.customer
CREATE TABLE mySchema.customer
(
 custkey      bigint NOT NULL COMMENT 'Customer identifier' CONSTRAINT PK_PK_2_customer PRIMARY KEY,
 name         string COMMENT 'Customer name',
 address      string COMMENT 'Billing address',
 nationkey    bigint COMMENT 'Customer nationality code',
 phone        string COMMENT 'Phone number of the customer',
 acctbal      decimal(18, 2),
 active_years bigint COMMENT 'Since when the customer is registered',
 mktsegment   string COMMENT 'Segment of the client',
 comment      string COMMENT 'Any additional comment about the customer',
 add           NOT NULL,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL -- From template: "w_cerated"
)
USING DELTA
 COMMENT 'Customer master data'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
