-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.region
CREATE TABLE mySchema.region
(
 regionkey    bigint,
 name         string,
 comment      string,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL -- From template: "w_cerated"
)
USING DELTA
 COMMENT 'region master data'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
