-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.prtsupp
CREATE TABLE mySchema.prtsupp
(
 prtkey       bigint NOT NULL,
 suppkey      bigint NOT NULL,
 availqty     int,
 supplycost   decimal(18, 2),
 comment      string,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL, -- From template: "w_cerated"
 CONSTRAINT PK_PK_2_prtsupp PRIMARY KEY (prtkey, suppkey)
)
USING DELTA
 COMMENT 'suppliers and their related stock'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
