-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.supplier
CREATE TABLE mySchema.supplier
(
 suppkey      bigint NOT NULL,
 nationkey    bigint NOT NULL CONSTRAINT FK_nation REFERENCES mySchema.nation,
 name         string,
 address      string,
 phone        string,
 acctbal      decimal(18, 2),
 comment      string,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL, -- From template: "w_cerated"
 CONSTRAINT PK_PK_2_supplier PRIMARY KEY (suppkey, nationkey)
)
USING DELTA
 COMMENT 'suppliers who source our inventory'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
