-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.orders
CREATE TABLE mySchema.orders
(
 orderkey      bigint NOT NULL CONSTRAINT PK_3_orders PRIMARY KEY,
 custkey       bigint NOT NULL CONSTRAINT FK_customer REFERENCES mySchema.customer,
 orderstatus   string,
 totalprice    decimal(18, 2),
 orderdate     date,
 orderpriority string,
 clerk         string,
 shippriority  int,
 comment       string,
 created_by    varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date  timestamp NOT NULL -- From template: "w_cerated"
)
USING DELTA
 COMMENT 'order totals'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
