-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.sub_prtsupp
CREATE TABLE mySchema.sub_prtsupp
(
 sub_parsupp_key bigint NOT NULL,
 sub_availqty    int,
 sub_supplycost  decimal(18, 2),
 created_by      varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date    timestamp NOT NULL -- From template: "w_cerated"
);
