-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.nation
CREATE TABLE mySchema.nation
(
 nationkey    bigint NOT NULL CONSTRAINT PK_3_nation PRIMARY KEY,
 name         string,
 regionkey    bigint,
 comment      string,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL -- From template: "w_cerated"
)
USING DELTA
 COMMENT 'nation grouping for sales regions'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
