-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.order_lineitem
CREATE TABLE mySchema.order_lineitem
(
 orderkey     bigint NOT NULL CONSTRAINT FK_orders REFERENCES mySchema.orders,
 linenumber   int NOT NULL,
 orderkey_1   bigint NOT NULL,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL, -- From template: "w_cerated"
 CONSTRAINT PK_1_order_lineitem PRIMARY KEY (orderkey, linenumber, orderkey_1),
 CONSTRAINT FK_lineitem FOREIGN KEY (linenumber, orderkey_1) REFERENCES mySchema.lineitem (linenumber, orderkey)
);
