-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** mySchema.lineitem
CREATE TABLE mySchema.lineitem
(
 linenumber    int NOT NULL,
 orderkey      bigint NOT NULL CONSTRAINT FK_orders REFERENCES mySchema.orders,
 prtkey        bigint,
 suppkey       bigint NOT NULL,
 nationkey     bigint NOT NULL,
 quantity      decimal(18, 2),
 extendedprice decimal(18, 2),
 discount      decimal(18, 2),
 tax           decimal(18, 2),
 returnflag    string,
 linestatus    string,
 shipdate      date,
 commitdate    date,
 receiptdate   date,
 shipinstruct  string,
 shipmode      string,
 comment       string,
 created_by    varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date  timestamp NOT NULL, -- From template: "w_cerated"
 CONSTRAINT PK_PK_2_lineitem PRIMARY KEY (linenumber, orderkey),
 CONSTRAINT FK_supplier FOREIGN KEY (suppkey, nationkey) REFERENCES mySchema.supplier (suppkey, nationkey)
)
USING DELTA
 COMMENT 'individual line item related to sales order'
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2);
