-- ************************* SqlDBM: Databricks *************************
-- ********* Generated by SqlDBM: xxx by hazal.sener@sqldbm.com *********

-- ************************************** vip_cust
CREATE TABLE vip_cust
(
 custkey      bigint NOT NULL COMMENT 'Customer identifier',
 vip_points   integer NOT NULL,
 created_by   varchar(50) NOT NULL, -- From template: "w_cerated"
 created_date timestamp NOT NULL -- From template: "w_cerated"
);
